# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-02 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_team',
            new_name='CompanyTeam',
        ),
    ]
