# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20190602_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyteam',
            name='team_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyteam',
            name='team_twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
