# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20190603_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyteam',
            name='team_description',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
