# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=100)),
                ('profile', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('show_on_profile', models.BooleanField(default=False)),
                ('protfolio_company_link', models.URLField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, max_length=10)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('portfolio_image_url', models.URLField(blank=True, null=True)),
                ('founders', models.ManyToManyField(blank=True, null=True, to='portfolio_company.Founders')),
            ],
        ),
    ]
