# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-28 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='company_subhead',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
