# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0002_portfoliocompany_company_subhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
