# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0003_portfoliocompany_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='founder'),
        ),
    ]
