# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-06 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0005_auto_20190606_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliocompany',
            old_name='portfolio_detail_url',
            new_name='portfolio_image_url',
        ),
    ]
