# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-06 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0007_auto_20190606_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
