# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='companyassociation',
            options={'verbose_name_plural': 'Company Association'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name_plural': 'Institute'},
        ),
        migrations.AlterModelOptions(
            name='insttitueassociation',
            options={'verbose_name_plural': 'Institute Association'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='companyassociation',
            name='end_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyassociation',
            name='start_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='connection',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insttitueassociation',
            name='end_date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insttitueassociation',
            name='start_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
