# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0002_auto_20180123_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
