# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0003_auto_20180129_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='linkedin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
