# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0004_auto_20180129_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='role',
            field=models.CharField(choices=[('Angel', 'Angel'), ('Expert', 'Expert'), ('GP', 'GP'), ('LP', 'LP')], max_length=30),
        ),
    ]
