# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0005_auto_20180129_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyassociation',
            name='end_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insttitueassociation',
            name='end_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
