# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0006_auto_20180129_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='img_file',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
