# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import pcontact.models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0007_auto_20180130_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyassociation',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='connection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to=pcontact.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='role',
            field=models.CharField(choices=[('Angel', 'Angel'), ('Expert', 'Expert'), ('GP', 'GP'), ('LP', 'LP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='insttitueassociation',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=200),
        ),
    ]
