# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 10:28
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0008_auto_20180201_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Angel', 'Angel'), ('Expert', 'Expert'), ('GP', 'GP'), ('LP', 'LP')], max_length=100),
        ),
    ]
