# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pcontact', '0009_auto_20180207_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='connection',
        ),
        migrations.AddField(
            model_name='contacts',
            name='connection',
            field=models.ManyToManyField(blank=True, null=True, to='users.CustomUser'),
        ),
    ]
