# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0010_auto_20180207_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='connection',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
