# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0011_auto_20180207_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insttitueassociation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='insttitueassociation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='insttitueassociation',
            name='year',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insttitueassociation',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
