# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0012_auto_20180220_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insttitueassociation',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
    ]
