# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0013_auto_20180220_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassociation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='companyassociation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='companyassociation',
            name='year',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
