# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0015_auto_20180220_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='past_investment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyassociation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Angel', 'Angel'), ('Expert', 'Expert'), ('GP', 'GP'), ('LP', 'LP')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
