# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0016_auto_20180226_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassociation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
