# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0017_companyassociation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pcontact.Tags'),
        ),
    ]
